kind: ConfigMap
apiVersion: v1
metadata:
  name: collectd-sidecar-config
data:
  node-sidecar-collectd.conf: |-
    #Hostname "<hostname_goes_here>"
    #Sets the hostname that identifies a host. If you omit this setting, 
    #the hostname will be determined using the gethostname(2) system call.
    #
    Interval "10"
    LoadPlugin network
   <Plugin interface>
    Interface "lo"
    IgnoreSelected true
  </Plugin>

    LoadPlugin network
    <Plugin network>
        Server "<destination_host_goes_here>" "25826" 
    </Plugin>
    #<Plugin "write_prometheus">
    #  Port "9103"
    #</Plugin>
    #Last line (collectd requires ‘\n’ at the last line)
---    
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
  labels:
    app: collectd-sidecar-pod-service
spec:
  volumes:
  - name: shared-logs
    emptyDir: {}

  # In the sidecar pattern, there is a main application
  # container and a sidecar container.
  containers:

  # Main application container
  - name: nginx
    image: nginx:1.7.9 
    command: ["/bin/sh"]
    ports:
      - containerPort: 80
    volumeMounts:
    - name: shared-logs
      mountPath: /usr/share/nginx/html
  

  # Sidecar container
  - name: sidecar-collectd-container
    # Simple sidecar: display log files using nginx.
    # In reality, this sidecar would be a custom image
    # that uploads logs to a third-party or storage service.
    image: docker.io/opnfv/barometer-collectd
    securityContext:
      privileged: true
    volumeMounts:
        - name: shared-logs
          mountPath: /var/lib/collectd/csv
        - mountPath: /var/cache/pmu
          name: pmu
          readOnly: false
        - mountPath: /opt/collectd/etc/
          name: config
          readOnly: true
        - mountPath: /var/run
          name: host-var-run
          readOnly: false
        - mountPath: /tmp
          name: host-tmp
          readOnly: false
        - mountPath: /var/lib/collectd
          name: host-var-lib-collectd
          readOnly: true
          # to run commands chroot in to the host
        - mountPath: /host
          name: host-slash
          readOnly: true
#        - mountPath: /proc
#          name: proc
#          readOnly: true
    volumes:
      - name: pmu
        hostPath:
          path: /var/cache/pmu
          type: DirectoryOrCreate
      - name: config
          configMap:
          name: collectd-config
          items:
          - key:  node-sidecar-collectd.conf
            path: collectd.conf
      - name: host-var-run
        hostPath:
          path: /var/run
      - name: host-tmp
        hostPath:
          path: /tmp
      - name: host-var-lib-collectd
        hostPath:
          path: /var/lib/collectd
      - name: host-slash
        hostPath:
          path: /
#      - name: proc
#        hostPath:
#          path: /proc
     terminationGracePeriodSeconds: 10
    restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: collectd-sidecar-pod-service
  labels:
    app: collectd-sidecar-pod-service
spec:
  ports:
  - port: 8081
    targetPort: 80
  selector:
    app: collectd-sidecar-pod-service
